# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jk < Formula
  desc ""
  homepage "https://github.com/longmenzhitong/jk"
  version "1.0.0"
  depends_on :macos

  url "https://github.com/longmenzhitong/jk/releases/download/v1.0.0/jk_1.0.0_darwin_all.tar.gz"
  sha256 "d53e7483935620de85c33061da56232855020e724b4a2971cd3b4d4fc2decbc6"

  def install
    bin.install "jk"
  end
end
