# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zodo < Formula
  desc ""
  homepage "https://github.com/longmenzhitong/zodo"
  version "0.0.3"
  depends_on :macos

  on_macos do
    url "https://github.com/longmenzhitong/zodo/releases/download/v0.0.3/zodo_0.0.3_darwin_all.tar.gz"
    sha256 "3f42d5dffce26f632b3c9fc0a380f0263dea27c12762c51f95b1345da6652f49"

    def install
      bin.install "zodo"
    end
  end
end
